// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/bvars.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bvar_mgig_cpp
Rcpp::List bvar_mgig_cpp(const int& S, const arma::mat& Y, const arma::mat& X, const Rcpp::List& prior, const Rcpp::List& starting_values, const arma::mat& sv_aux_mix, const bool homoskedastic, const bool centred_sv, const bool normal, const int thin, const bool show_progress);
static SEXP _bvars_bvar_mgig_cpp_try(SEXP SSEXP, SEXP YSEXP, SEXP XSEXP, SEXP priorSEXP, SEXP starting_valuesSEXP, SEXP sv_aux_mixSEXP, SEXP homoskedasticSEXP, SEXP centred_svSEXP, SEXP normalSEXP, SEXP thinSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type starting_values(starting_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sv_aux_mix(sv_aux_mixSEXP);
    Rcpp::traits::input_parameter< const bool >::type homoskedastic(homoskedasticSEXP);
    Rcpp::traits::input_parameter< const bool >::type centred_sv(centred_svSEXP);
    Rcpp::traits::input_parameter< const bool >::type normal(normalSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(bvar_mgig_cpp(S, Y, X, prior, starting_values, sv_aux_mix, homoskedastic, centred_sv, normal, thin, show_progress));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_bvar_mgig_cpp(SEXP SSEXP, SEXP YSEXP, SEXP XSEXP, SEXP priorSEXP, SEXP starting_valuesSEXP, SEXP sv_aux_mixSEXP, SEXP homoskedasticSEXP, SEXP centred_svSEXP, SEXP normalSEXP, SEXP thinSEXP, SEXP show_progressSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_bvar_mgig_cpp_try(SSEXP, YSEXP, XSEXP, priorSEXP, starting_valuesSEXP, sv_aux_mixSEXP, homoskedasticSEXP, centred_svSEXP, normalSEXP, thinSEXP, show_progressSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// Sigma2B
arma::cube Sigma2B(arma::cube& posterior_Sigma_c);
static SEXP _bvars_Sigma2B_try(SEXP posterior_Sigma_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_Sigma_c(posterior_Sigma_cSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigma2B(posterior_Sigma_c));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_Sigma2B(SEXP posterior_Sigma_cSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_Sigma2B_try(posterior_Sigma_cSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// compute_variance_decompositions
arma::field<arma::cube> compute_variance_decompositions(arma::cube& posterior_Sigma, arma::cube& posterior_A, const int horizon, const int p);
static SEXP _bvars_compute_variance_decompositions_try(SEXP posterior_SigmaSEXP, SEXP posterior_ASEXP, SEXP horizonSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_Sigma(posterior_SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_A(posterior_ASEXP);
    Rcpp::traits::input_parameter< const int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_variance_decompositions(posterior_Sigma, posterior_A, horizon, p));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_compute_variance_decompositions(SEXP posterior_SigmaSEXP, SEXP posterior_ASEXP, SEXP horizonSEXP, SEXP pSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_compute_variance_decompositions_try(posterior_SigmaSEXP, posterior_ASEXP, horizonSEXP, pSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// compute_fitted_values
arma::cube compute_fitted_values(arma::cube& posterior_A, arma::cube& posterior_Sigma, arma::mat& posterior_sigma2, arma::mat& X);
static SEXP _bvars_compute_fitted_values_try(SEXP posterior_ASEXP, SEXP posterior_SigmaSEXP, SEXP posterior_sigma2SEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_A(posterior_ASEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_Sigma(posterior_SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type posterior_sigma2(posterior_sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_fitted_values(posterior_A, posterior_Sigma, posterior_sigma2, X));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_compute_fitted_values(SEXP posterior_ASEXP, SEXP posterior_SigmaSEXP, SEXP posterior_sigma2SEXP, SEXP XSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_compute_fitted_values_try(posterior_ASEXP, posterior_SigmaSEXP, posterior_sigma2SEXP, XSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// compute_shocks
arma::cube compute_shocks(arma::cube& posterior_A, arma::mat& Y, arma::mat& X);
static SEXP _bvars_compute_shocks_try(SEXP posterior_ASEXP, SEXP YSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_A(posterior_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_shocks(posterior_A, Y, X));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_compute_shocks(SEXP posterior_ASEXP, SEXP YSEXP, SEXP XSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_compute_shocks_try(posterior_ASEXP, YSEXP, XSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// forecast_bvarGIG
Rcpp::List forecast_bvarGIG(arma::cube& posterior_Sigma, arma::cube& posterior_A, arma::mat& forecast_sigma2, arma::vec& X_T, arma::mat& exogenous_forecast, arma::mat& cond_forecast, const int& horizon);
static SEXP _bvars_forecast_bvarGIG_try(SEXP posterior_SigmaSEXP, SEXP posterior_ASEXP, SEXP forecast_sigma2SEXP, SEXP X_TSEXP, SEXP exogenous_forecastSEXP, SEXP cond_forecastSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_Sigma(posterior_SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_A(posterior_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type forecast_sigma2(forecast_sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type X_T(X_TSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type exogenous_forecast(exogenous_forecastSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cond_forecast(cond_forecastSEXP);
    Rcpp::traits::input_parameter< const int& >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_bvarGIG(posterior_Sigma, posterior_A, forecast_sigma2, X_T, exogenous_forecast, cond_forecast, horizon));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_forecast_bvarGIG(SEXP posterior_SigmaSEXP, SEXP posterior_ASEXP, SEXP forecast_sigma2SEXP, SEXP X_TSEXP, SEXP exogenous_forecastSEXP, SEXP cond_forecastSEXP, SEXP horizonSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_forecast_bvarGIG_try(posterior_SigmaSEXP, posterior_ASEXP, forecast_sigma2SEXP, X_TSEXP, exogenous_forecastSEXP, cond_forecastSEXP, horizonSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// forecast_sigma2_sv1
arma::mat forecast_sigma2_sv1(arma::vec& posterior_h_T, arma::vec& posterior_rho, arma::vec& posterior_omega, const int& horizon);
static SEXP _bvars_forecast_sigma2_sv1_try(SEXP posterior_h_TSEXP, SEXP posterior_rhoSEXP, SEXP posterior_omegaSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type posterior_h_T(posterior_h_TSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type posterior_rho(posterior_rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type posterior_omega(posterior_omegaSEXP);
    Rcpp::traits::input_parameter< const int& >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_sigma2_sv1(posterior_h_T, posterior_rho, posterior_omega, horizon));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_forecast_sigma2_sv1(SEXP posterior_h_TSEXP, SEXP posterior_rhoSEXP, SEXP posterior_omegaSEXP, SEXP horizonSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_forecast_sigma2_sv1_try(posterior_h_TSEXP, posterior_rhoSEXP, posterior_omegaSEXP, horizonSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// forecast_lambda_t1
arma::mat forecast_lambda_t1(arma::vec& posterior_df, const int& horizon);
static SEXP _bvars_forecast_lambda_t1_try(SEXP posterior_dfSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type posterior_df(posterior_dfSEXP);
    Rcpp::traits::input_parameter< const int& >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_lambda_t1(posterior_df, horizon));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_forecast_lambda_t1(SEXP posterior_dfSEXP, SEXP horizonSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_forecast_lambda_t1_try(posterior_dfSEXP, horizonSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// do_rmatnorm1
arma::mat do_rmatnorm1(const arma::mat& M, const arma::mat& V, const arma::mat& S);
static SEXP _bvars_do_rmatnorm1_try(SEXP MSEXP, SEXP VSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(do_rmatnorm1(M, V, S));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_do_rmatnorm1(SEXP MSEXP, SEXP VSEXP, SEXP SSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_do_rmatnorm1_try(MSEXP, VSEXP, SSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_ASigma
arma::field<arma::mat> sample_ASigma(const arma::mat& Y, const arma::mat& X, arma::mat& aux_V_inv, arma::vec& aux_Omega_diag_inv, const Rcpp::List& prior);
static SEXP _bvars_sample_ASigma_try(SEXP YSEXP, SEXP XSEXP, SEXP aux_V_invSEXP, SEXP aux_Omega_diag_invSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type aux_V_inv(aux_V_invSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type aux_Omega_diag_inv(aux_Omega_diag_invSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ASigma(Y, X, aux_V_inv, aux_Omega_diag_inv, prior));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_sample_ASigma(SEXP YSEXP, SEXP XSEXP, SEXP aux_V_invSEXP, SEXP aux_Omega_diag_invSEXP, SEXP priorSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_sample_ASigma_try(YSEXP, XSEXP, aux_V_invSEXP, aux_Omega_diag_invSEXP, priorSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_lambda
arma::vec sample_lambda(double& aux_df, arma::vec& U, const int N);
static SEXP _bvars_sample_lambda_try(SEXP aux_dfSEXP, SEXP USEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double& >::type aux_df(aux_dfSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_lambda(aux_df, U, N));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_sample_lambda(SEXP aux_dfSEXP, SEXP USEXP, SEXP NSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_sample_lambda_try(aux_dfSEXP, USEXP, NSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// log_kernel_df
double log_kernel_df(const double& aux_df, const arma::vec& aux_lambda);
static SEXP _bvars_log_kernel_df_try(SEXP aux_dfSEXP, SEXP aux_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double& >::type aux_df(aux_dfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type aux_lambda(aux_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_kernel_df(aux_df, aux_lambda));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_log_kernel_df(SEXP aux_dfSEXP, SEXP aux_lambdaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_log_kernel_df_try(aux_dfSEXP, aux_lambdaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_df
Rcpp::List sample_df(double& aux_df, double& adaptive_scale, const arma::vec& aux_lambda, const int& s, const arma::vec& adptive_alpha_gamma);
static SEXP _bvars_sample_df_try(SEXP aux_dfSEXP, SEXP adaptive_scaleSEXP, SEXP aux_lambdaSEXP, SEXP sSEXP, SEXP adptive_alpha_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double& >::type aux_df(aux_dfSEXP);
    Rcpp::traits::input_parameter< double& >::type adaptive_scale(adaptive_scaleSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type aux_lambda(aux_lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type adptive_alpha_gamma(adptive_alpha_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_df(aux_df, adaptive_scale, aux_lambda, s, adptive_alpha_gamma));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_sample_df(SEXP aux_dfSEXP, SEXP adaptive_scaleSEXP, SEXP aux_lambdaSEXP, SEXP sSEXP, SEXP adptive_alpha_gammaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_sample_df_try(aux_dfSEXP, adaptive_scaleSEXP, aux_lambdaSEXP, sSEXP, adptive_alpha_gammaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sv_aux_mix_n
arma::mat sv_aux_mix_n(const int N);
static SEXP _bvars_sv_aux_mix_n_try(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sv_aux_mix_n(N));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_sv_aux_mix_n(SEXP NSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_sv_aux_mix_n_try(NSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// find_mixture_indicator_cdf
arma::vec find_mixture_indicator_cdf(const arma::vec& datanorm, const arma::mat& aux_mix);
static SEXP _bvars_find_mixture_indicator_cdf_try(SEXP datanormSEXP, SEXP aux_mixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type datanorm(datanormSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aux_mix(aux_mixSEXP);
    rcpp_result_gen = Rcpp::wrap(find_mixture_indicator_cdf(datanorm, aux_mix));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_find_mixture_indicator_cdf(SEXP datanormSEXP, SEXP aux_mixSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_find_mixture_indicator_cdf_try(datanormSEXP, aux_mixSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// svar_nc1
Rcpp::List svar_nc1(arma::vec& aux_h, double& aux_rho, double& aux_omega, double& aux_sigma2v, double& aux_sigma2_omega, double& aux_s_, arma::uvec& aux_S, const arma::vec& u, const Rcpp::List& prior, const arma::mat& aux_mix, bool sample_s_, bool debug);
static SEXP _bvars_svar_nc1_try(SEXP aux_hSEXP, SEXP aux_rhoSEXP, SEXP aux_omegaSEXP, SEXP aux_sigma2vSEXP, SEXP aux_sigma2_omegaSEXP, SEXP aux_s_SEXP, SEXP aux_SSEXP, SEXP uSEXP, SEXP priorSEXP, SEXP aux_mixSEXP, SEXP sample_s_SEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type aux_h(aux_hSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_rho(aux_rhoSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_omega(aux_omegaSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_sigma2v(aux_sigma2vSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_sigma2_omega(aux_sigma2_omegaSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_s_(aux_s_SEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type aux_S(aux_SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aux_mix(aux_mixSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_s_(sample_s_SEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(svar_nc1(aux_h, aux_rho, aux_omega, aux_sigma2v, aux_sigma2_omega, aux_s_, aux_S, u, prior, aux_mix, sample_s_, debug));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_svar_nc1(SEXP aux_hSEXP, SEXP aux_rhoSEXP, SEXP aux_omegaSEXP, SEXP aux_sigma2vSEXP, SEXP aux_sigma2_omegaSEXP, SEXP aux_s_SEXP, SEXP aux_SSEXP, SEXP uSEXP, SEXP priorSEXP, SEXP aux_mixSEXP, SEXP sample_s_SEXP, SEXP debugSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_svar_nc1_try(aux_hSEXP, aux_rhoSEXP, aux_omegaSEXP, aux_sigma2vSEXP, aux_sigma2_omegaSEXP, aux_s_SEXP, aux_SSEXP, uSEXP, priorSEXP, aux_mixSEXP, sample_s_SEXP, debugSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// svar_ce1
Rcpp::List svar_ce1(arma::vec& aux_h, double& aux_rho, double& aux_omega, double& aux_sigma2v, double& aux_sigma2_omega, double& aux_s_, arma::uvec& aux_S, const arma::vec& u, const Rcpp::List& prior, const arma::mat& aux_mix, bool sample_s_);
static SEXP _bvars_svar_ce1_try(SEXP aux_hSEXP, SEXP aux_rhoSEXP, SEXP aux_omegaSEXP, SEXP aux_sigma2vSEXP, SEXP aux_sigma2_omegaSEXP, SEXP aux_s_SEXP, SEXP aux_SSEXP, SEXP uSEXP, SEXP priorSEXP, SEXP aux_mixSEXP, SEXP sample_s_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type aux_h(aux_hSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_rho(aux_rhoSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_omega(aux_omegaSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_sigma2v(aux_sigma2vSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_sigma2_omega(aux_sigma2_omegaSEXP);
    Rcpp::traits::input_parameter< double& >::type aux_s_(aux_s_SEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type aux_S(aux_SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aux_mix(aux_mixSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_s_(sample_s_SEXP);
    rcpp_result_gen = Rcpp::wrap(svar_ce1(aux_h, aux_rho, aux_omega, aux_sigma2v, aux_sigma2_omega, aux_s_, aux_S, u, prior, aux_mix, sample_s_));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _bvars_svar_ce1(SEXP aux_hSEXP, SEXP aux_rhoSEXP, SEXP aux_omegaSEXP, SEXP aux_sigma2vSEXP, SEXP aux_sigma2_omegaSEXP, SEXP aux_s_SEXP, SEXP aux_SSEXP, SEXP uSEXP, SEXP priorSEXP, SEXP aux_mixSEXP, SEXP sample_s_SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_bvars_svar_ce1_try(aux_hSEXP, aux_rhoSEXP, aux_omegaSEXP, aux_sigma2vSEXP, aux_sigma2_omegaSEXP, aux_s_SEXP, aux_SSEXP, uSEXP, priorSEXP, aux_mixSEXP, sample_s_SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _bvars_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("Rcpp::List(*bvar_mgig_cpp)(const int&,const arma::mat&,const arma::mat&,const Rcpp::List&,const Rcpp::List&,const arma::mat&,const bool,const bool,const bool,const int,const bool)");
        signatures.insert("arma::cube(*Sigma2B)(arma::cube&)");
        signatures.insert("arma::field<arma::cube>(*compute_variance_decompositions)(arma::cube&,arma::cube&,const int,const int)");
        signatures.insert("arma::cube(*compute_fitted_values)(arma::cube&,arma::cube&,arma::mat&,arma::mat&)");
        signatures.insert("arma::cube(*compute_shocks)(arma::cube&,arma::mat&,arma::mat&)");
        signatures.insert("Rcpp::List(*forecast_bvarGIG)(arma::cube&,arma::cube&,arma::mat&,arma::vec&,arma::mat&,arma::mat&,const int&)");
        signatures.insert("arma::mat(*forecast_sigma2_sv1)(arma::vec&,arma::vec&,arma::vec&,const int&)");
        signatures.insert("arma::mat(*forecast_lambda_t1)(arma::vec&,const int&)");
        signatures.insert("arma::mat(*do_rmatnorm1)(const arma::mat&,const arma::mat&,const arma::mat&)");
        signatures.insert("arma::field<arma::mat>(*sample_ASigma)(const arma::mat&,const arma::mat&,arma::mat&,arma::vec&,const Rcpp::List&)");
        signatures.insert("arma::vec(*sample_lambda)(double&,arma::vec&,const int)");
        signatures.insert("double(*log_kernel_df)(const double&,const arma::vec&)");
        signatures.insert("Rcpp::List(*sample_df)(double&,double&,const arma::vec&,const int&,const arma::vec&)");
        signatures.insert("arma::mat(*sv_aux_mix_n)(const int)");
        signatures.insert("arma::vec(*find_mixture_indicator_cdf)(const arma::vec&,const arma::mat&)");
        signatures.insert("Rcpp::List(*svar_nc1)(arma::vec&,double&,double&,double&,double&,double&,arma::uvec&,const arma::vec&,const Rcpp::List&,const arma::mat&,bool,bool)");
        signatures.insert("Rcpp::List(*svar_ce1)(arma::vec&,double&,double&,double&,double&,double&,arma::uvec&,const arma::vec&,const Rcpp::List&,const arma::mat&,bool)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _bvars_RcppExport_registerCCallable() { 
    R_RegisterCCallable("bvars", "_bvars_bvar_mgig_cpp", (DL_FUNC)_bvars_bvar_mgig_cpp_try);
    R_RegisterCCallable("bvars", "_bvars_Sigma2B", (DL_FUNC)_bvars_Sigma2B_try);
    R_RegisterCCallable("bvars", "_bvars_compute_variance_decompositions", (DL_FUNC)_bvars_compute_variance_decompositions_try);
    R_RegisterCCallable("bvars", "_bvars_compute_fitted_values", (DL_FUNC)_bvars_compute_fitted_values_try);
    R_RegisterCCallable("bvars", "_bvars_compute_shocks", (DL_FUNC)_bvars_compute_shocks_try);
    R_RegisterCCallable("bvars", "_bvars_forecast_bvarGIG", (DL_FUNC)_bvars_forecast_bvarGIG_try);
    R_RegisterCCallable("bvars", "_bvars_forecast_sigma2_sv1", (DL_FUNC)_bvars_forecast_sigma2_sv1_try);
    R_RegisterCCallable("bvars", "_bvars_forecast_lambda_t1", (DL_FUNC)_bvars_forecast_lambda_t1_try);
    R_RegisterCCallable("bvars", "_bvars_do_rmatnorm1", (DL_FUNC)_bvars_do_rmatnorm1_try);
    R_RegisterCCallable("bvars", "_bvars_sample_ASigma", (DL_FUNC)_bvars_sample_ASigma_try);
    R_RegisterCCallable("bvars", "_bvars_sample_lambda", (DL_FUNC)_bvars_sample_lambda_try);
    R_RegisterCCallable("bvars", "_bvars_log_kernel_df", (DL_FUNC)_bvars_log_kernel_df_try);
    R_RegisterCCallable("bvars", "_bvars_sample_df", (DL_FUNC)_bvars_sample_df_try);
    R_RegisterCCallable("bvars", "_bvars_sv_aux_mix_n", (DL_FUNC)_bvars_sv_aux_mix_n_try);
    R_RegisterCCallable("bvars", "_bvars_find_mixture_indicator_cdf", (DL_FUNC)_bvars_find_mixture_indicator_cdf_try);
    R_RegisterCCallable("bvars", "_bvars_svar_nc1", (DL_FUNC)_bvars_svar_nc1_try);
    R_RegisterCCallable("bvars", "_bvars_svar_ce1", (DL_FUNC)_bvars_svar_ce1_try);
    R_RegisterCCallable("bvars", "_bvars_RcppExport_validate", (DL_FUNC)_bvars_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_bvars_bvar_mgig_cpp", (DL_FUNC) &_bvars_bvar_mgig_cpp, 11},
    {"_bvars_Sigma2B", (DL_FUNC) &_bvars_Sigma2B, 1},
    {"_bvars_compute_variance_decompositions", (DL_FUNC) &_bvars_compute_variance_decompositions, 4},
    {"_bvars_compute_fitted_values", (DL_FUNC) &_bvars_compute_fitted_values, 4},
    {"_bvars_compute_shocks", (DL_FUNC) &_bvars_compute_shocks, 3},
    {"_bvars_forecast_bvarGIG", (DL_FUNC) &_bvars_forecast_bvarGIG, 7},
    {"_bvars_forecast_sigma2_sv1", (DL_FUNC) &_bvars_forecast_sigma2_sv1, 4},
    {"_bvars_forecast_lambda_t1", (DL_FUNC) &_bvars_forecast_lambda_t1, 2},
    {"_bvars_do_rmatnorm1", (DL_FUNC) &_bvars_do_rmatnorm1, 3},
    {"_bvars_sample_ASigma", (DL_FUNC) &_bvars_sample_ASigma, 5},
    {"_bvars_sample_lambda", (DL_FUNC) &_bvars_sample_lambda, 3},
    {"_bvars_log_kernel_df", (DL_FUNC) &_bvars_log_kernel_df, 2},
    {"_bvars_sample_df", (DL_FUNC) &_bvars_sample_df, 5},
    {"_bvars_sv_aux_mix_n", (DL_FUNC) &_bvars_sv_aux_mix_n, 1},
    {"_bvars_find_mixture_indicator_cdf", (DL_FUNC) &_bvars_find_mixture_indicator_cdf, 2},
    {"_bvars_svar_nc1", (DL_FUNC) &_bvars_svar_nc1, 12},
    {"_bvars_svar_ce1", (DL_FUNC) &_bvars_svar_ce1, 11},
    {"_bvars_RcppExport_registerCCallable", (DL_FUNC) &_bvars_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bvars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
